<#
.SYNOPSIS
    Verifies snapshot integrity using hashes.txt and manifest.json.
.DESCRIPTION
    Reads hashes.txt generated by SnapshotExporter and recomputes SHA256 for each listed file.
    Returns non-zero exit code when any mismatch or missing file is found.
.PARAMETER SnapshotPath
    Path to one snapshot folder (contains timeline.json/entities.json/manifest.json/hashes.txt).
.PARAMETER SnapshotRoot
    Root path containing one or more snapshot_* folders.
.PARAMETER Recurse
    When used with SnapshotRoot, scan snapshot_* folders recursively.
.EXAMPLE
    .\VerifySnapshotIntegrity.ps1 -SnapshotPath "C:\Collect\snapshot_20260305_010203"
.EXAMPLE
    .\VerifySnapshotIntegrity.ps1 -SnapshotRoot "C:\Collect" -Recurse
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true, ParameterSetName = "single")]
    [string] $SnapshotPath,
    [Parameter(Mandatory = $true, ParameterSetName = "batch")]
    [string] $SnapshotRoot,
    [Parameter(ParameterSetName = "batch")]
    [switch] $Recurse
)

$ErrorActionPreference = "Stop"

function Test-OneSnapshot {
    param([Parameter(Mandatory = $true)][string] $Path)
    if (-not (Test-Path -LiteralPath $Path)) {
        return [PSCustomObject]@{ Path = $Path; Success = $false; Error = "Snapshot path not found"; VerifiedFiles = 0 }
    }

    $hashesPath = Join-Path $Path "hashes.txt"
    if (-not (Test-Path -LiteralPath $hashesPath)) {
        return [PSCustomObject]@{ Path = $Path; Success = $false; Error = "hashes.txt not found"; VerifiedFiles = 0 }
    }

    $lines = Get-Content -Path $hashesPath
    $entries = @()
    foreach ($line in $lines) {
        $trim = $line.Trim()
        if (-not $trim -or $trim.StartsWith("#")) { continue }
        $parts = $trim -split "\s{2,}", 2
        if ($parts.Count -ne 2) { continue }
        $entries += [PSCustomObject]@{
            Hash = $parts[0].Trim().ToLowerInvariant()
            RelativePath = $parts[1].Trim()
        }
    }

    if ($entries.Count -eq 0) {
        return [PSCustomObject]@{ Path = $Path; Success = $false; Error = "No hash entries found in hashes.txt"; VerifiedFiles = 0 }
    }

    $missing = @()
    $mismatch = @()
    foreach ($entry in $entries) {
        $filePath = Join-Path $Path $entry.RelativePath
        if (-not (Test-Path -LiteralPath $filePath)) {
            $missing += $entry.RelativePath
            continue
        }
        $actual = (Get-FileHash -Path $filePath -Algorithm SHA256).Hash.ToLowerInvariant()
        if ($actual -ne $entry.Hash) {
            $mismatch += [PSCustomObject]@{
                RelativePath = $entry.RelativePath
                Expected = $entry.Hash
                Actual = $actual
            }
        }
    }

    if ($missing.Count -gt 0 -or $mismatch.Count -gt 0) {
        $err = @()
        if ($missing.Count -gt 0) { $err += ("Missing: " + ($missing -join ", ")) }
        if ($mismatch.Count -gt 0) { $err += ("Mismatch: " + (($mismatch | Select-Object -ExpandProperty RelativePath) -join ", ")) }
        return [PSCustomObject]@{ Path = $Path; Success = $false; Error = ($err -join " | "); VerifiedFiles = $entries.Count }
    }

    return [PSCustomObject]@{ Path = $Path; Success = $true; Error = $null; VerifiedFiles = $entries.Count }
}

if ($PSCmdlet.ParameterSetName -eq "single") {
    $result = Test-OneSnapshot -Path $SnapshotPath
    if ($result.Success) {
        Write-Host "Snapshot integrity OK"
        Write-Host ("Verified files: {0}" -f $result.VerifiedFiles)
        exit 0
    }
    Write-Host "Snapshot integrity FAILED"
    Write-Host ("Path: {0}" -f $result.Path)
    Write-Host ("Error: {0}" -f $result.Error)
    exit 1
}

if (-not (Test-Path -LiteralPath $SnapshotRoot)) {
    Write-Error "Snapshot root path not found: $SnapshotRoot"
    exit 2
}

$searchOption = if ($Recurse) { "AllDirectories" } else { "TopDirectoryOnly" }
$snapshots = Get-ChildItem -Path $SnapshotRoot -Directory -Filter "snapshot_*" -ErrorAction SilentlyContinue
if ($Recurse) {
    $snapshots = Get-ChildItem -Path $SnapshotRoot -Directory -Recurse -ErrorAction SilentlyContinue | Where-Object { $_.Name -like "snapshot_*" }
}

if (-not $snapshots -or $snapshots.Count -eq 0) {
    Write-Error "No snapshot_* folders found under: $SnapshotRoot"
    exit 3
}

$failed = 0
foreach ($s in $snapshots) {
    $result = Test-OneSnapshot -Path $s.FullName
    if ($result.Success) {
        Write-Host ("OK: {0} (files={1})" -f $result.Path, $result.VerifiedFiles)
    }
    else {
        $failed++
        Write-Host ("FAIL: {0}" -f $result.Path)
        Write-Host ("  Error: {0}" -f $result.Error)
    }
}

if ($failed -gt 0) {
    Write-Host ("Batch integrity FAILED: {0}/{1} snapshots failed." -f $failed, $snapshots.Count)
    exit 1
}

Write-Host ("Batch integrity OK: {0} snapshots verified." -f $snapshots.Count)
exit 0

